nav:
    - item:
        destination:    home
        label:          Home
        view:           FirstView
    - item:
        destination:    media
        label:          Media Section
        view:           SecondView
    - item:
        destination:    newsletter
        label:          Newsletter Signup
        view:           SecondView
    - item:
        destination:    download
        label:          Download Section
        view:           SecondView
        - item:
            destination:    trailer
            label:          Trailer Section
            view:           SecondView
        - item:
            destination:    screenshots
            label:          Screenshots Section
            view:           SecondView
        - item:
            destination:    wallpapers
            label:          Wallpapers Section
            view:           SecondView
    - item:
        destination:    blog
        label:          Blog and News
        view:           SecondView
    - item:
        destination:    community
        label:          Community
        view:           ThirdView
    - item:
        destination:    preorder
        label:          Preorder
        view:           FourthView
    - item:
        destination:    buy
        label:          Buy Now
        view:           FourthView

tagline: This is a tagline, right here.
swap_assets: Swap those assets!

external_links:
    dzone:
        name: dzone
        destination: http://www.dzone.com/
        label: DZone!
    github:
        name: github
        destination: http://github.com/
        label: github
    birdbase:
        name: birdbase
        destination: http://www.birdbase.org/
        label: BirdBase
        