nav:
    - item:
        destination:    home
        label:          Home
        view:           HomeView
    - item:
        destination:    media
        label:          Media Section
        view:           MediaView
        subviews:
            - item:
                destination:    mediatrailer
                label:          Media Trailer Section
                view:           MediaTrailerView
            - item:
                destination:    mediascreenshots
                label:          Media Screenshots Section
                view:           MediaScreenshotsView
            - item:
                destination:    mediawallpapers
                label:          Media Wallpapers Section
                view:           MediaWallpapersView
    - item:
        destination:    newsletter
        label:          Newsletter Signup
        view:           NewsletterView
    - item:
        destination:    download
        label:          Download Section
        view:           DownloadView
    - item:
        destination:    news
        label:          Weblog/News
        view:           NewsView
    - item:
        destination:    community
        label:          Community
        view:           CommunityView
    - item:
        destination:    preorder
        label:          Preorder
        view:           FourthView
    - item:
        destination:    buy
        label:          Buy Now
        view:           FourthView

lorem: Pellentesque nibh felis, eleifend id, commodo in, interdum vitae, leo. Praesent eu elit. Ut eu ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Maecenas elementum augue nec nisl. Proin auctor lorem at nibh. Curabitur nulla purus, feugiat id, elementum in, lobortis quis, pede. Vivamus sodales adipiscing sapien. Vestibulum posuere nulla eget wisi. Integer volutpat ligula eget enim. Suspendisse vitae arcu. Quisque pellentesque. Nullam consequat, sem vitae rhoncus tristique, mauris nulla fermentum est, bibendum ullamcorper sapien magna et quam. Sed dapibus vehicula odio. Proin bibendum gravida nisl. Fusce lorem. Phasellus sagittis, nulla in hendrerit laoreet, libero lacus feugiat urna, eget hendrerit pede magna vitae lorem. Praesent mauris.
strings:
    bluebutton: A Blue Button!
    redbutton: A Red Button!
    yellowbutton: A Yellow Button!
    purplebutton: A Purple Button!
    tagline: This is a tagline, right here. Good Morning %s!
    swap_assets: Swap those assets!
    secondviewselected: This is the <b>second</b> view of the %s application. Hurrah for the colour %s! Some more %s would really brighten up this view.

external_links:
    dzone:
        name: dzone
        destination: http://www.dzone.com/
        label: DZone!
    github:
        name: github
        destination: http://github.com/
        label: github
    birdbase:
        name: birdbase
        destination: http://www.birdbase.org/
        label: BirdBase
        